name = "Hugo Leonard"
license = "MIT"
licenselink = "https://github.com/vai/hugo-leonard-theme/blob/master/LICENSE"
description = "Hugo Leonard is a riff on Hugo Winston"

homepage = "https://github.com/vai/hugo-leonard-theme"
demosite = "https://ineffable.co.za"

tags = ["blog", "minimal", "clean", "zerostatic"]
features = ["blog"]

[author]
  name = "Matthew McLeod"
  homepage = "https://ineffable.co.za"
